### ISSUE TITLE
MKL is not supported for WSL setup

### ISSUE THREAD

**Issue by scdivi** [evalf/nutils#673]
If we run a script with `NUTILS_MATRIX=MKL python myscript.py` then it return an error `nutils.matrix.BackendNotAvailable: the Intel MKL matrix backend requires libmkl to be installed (try: pip install mkl)` though mkl python package is already installed.

**Comment by joostvanzwieten** [comment]
We don't support MKL installed via pip out of the box. You have two options.

1. Install MKL via the Linux distribution's package manager. If you are using Debian you can install MKL using `apt install libmkl-rt` after [adding `non-free` to the selection of components in your `/etc/apt/sources.list`](https://stackoverflow.com/a/65795202). This probably works for Ubuntu as well, but you should ensure component `multiverse` is enabled instead of `non-free`. I'm not sure if `multiverse` is enabled by default.
2. Add the directory where pip installs the MKL libraries to the `LD_LIBRARY_PATH` environment variable. We've had some problems with MKL from pip in the past due to missing libraries.

I'm closing the issue for now. Please reopen if the above doesn't work for you.
