### ISSUE TITLE
incompatibility with NumPy 1.19 (and possibly other versions)

### ISSUE THREAD

**Issue by CVerhoosel** [evalf/nutils#694]
We noticed that some students in our class run into issues with Nutils code because their Numpy installation (typically installed through anaconda for Windows) is not completely up to date (we have seen it for 1.19). Specifically the numpy.typing module is not found then. Is this version dependency something to check in Nutils?

_Originally posted by @CVerhoosel in https://github.com/evalf/nutils/discussions/693_

**Comment by joostvanzwieten** [comment]
All unittests of Nutils v7 pass with NumPy 1.19.5 on Linux. All unittests pass with Anaconda (3, 2022.05) on Linux as well. Can you maybe paste a traceback here? Which version of Nutils are the students using?

**Comment by joostvanzwieten** [comment]
I've looked into this again and found out that the problem is caused by Meshio, not Nutils. [Meshio requires Numpy version 1.20 or higher](https://github.com/nschloe/meshio/pull/1236), most likely as of Meshio version 5.0.6, commit [c24e5ba](https://github.com/nschloe/meshio/commit/c24e5ba6334a1619b6ba5b2a67f1c2c7f1279c6c). When installing any package using pip, it is probably best to add [`--upgrade`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-U) which, together with the default [`--upgrade-strategy only-if-needed`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-upgrade-strategy), ensures that dependencies are upgraded if necessary.
